[rules.alloc-only-in-prelude]
include = ["pkgs/**/*.rs"]
exclude = ["**/prelude.rs", "pkgs/types/src/entity.rs"]
block = ['alloc::']
message = "use crate::prelude instead of alloc:: directly"

[rules.disambiguate-serde-derive]
include = ["pkgs/**/*.rs"]
block = ['derive\(serde::']
allow = ['derive\(::serde::']
message = "use ::serde:: instead of serde:: in derive"
