#!/usr/bin/env python3
# coding: latin-1

#
# Copyright (c) 2026-present, The Dash Core developers
# SPDX-License-Identifier: MIT
# See the accompanying file LICENSE or https://opensource.org/license/MIT
#

"""Runs CodeQL queries against the workspace."""

from __future__ import annotations

import datetime
import json
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from common import (
  RETCODE_ERR,
  RETCODE_PASS,
  RETCODE_SKIP,
  find_up,
  is_workspace_root,
  require_bin,
)


@dataclass(frozen=True)
class SarifRegion:
  start_line: int = 0

  @classmethod
  def from_json(cls, raw: dict[str, Any]) -> SarifRegion:
    return cls(start_line=raw.get("startLine", 0))


@dataclass(frozen=True)
class SarifArtifactLocation:
  uri: str = "?"

  @classmethod
  def from_json(
    cls, raw: dict[str, Any],
  ) -> SarifArtifactLocation:
    return cls(uri=raw.get("uri", "?"))


@dataclass(frozen=True)
class SarifPhysicalLocation:
  artifact_location: SarifArtifactLocation = field(
    default_factory=SarifArtifactLocation,
  )
  region: SarifRegion = field(default_factory=SarifRegion)

  @classmethod
  def from_json(
    cls, raw: dict[str, Any],
  ) -> SarifPhysicalLocation:
    return cls(
      artifact_location=SarifArtifactLocation.from_json(
        raw.get("artifactLocation", {}),
      ),
      region=SarifRegion.from_json(raw.get("region", {})),
    )


@dataclass(frozen=True)
class SarifLocation:
  physical_location: SarifPhysicalLocation = field(
    default_factory=SarifPhysicalLocation,
  )

  @classmethod
  def from_json(cls, raw: dict[str, Any]) -> SarifLocation:
    return cls(
      physical_location=SarifPhysicalLocation.from_json(
        raw.get("physicalLocation", {}),
      ),
    )


@dataclass(frozen=True)
class SarifMessage:
  text: str = ""

  @classmethod
  def from_json(cls, raw: dict[str, Any]) -> SarifMessage:
    return cls(text=raw.get("text", ""))


@dataclass(frozen=True)
class SarifResult:
  message: SarifMessage = field(default_factory=SarifMessage)
  locations: list[SarifLocation] = field(default_factory=list)

  @classmethod
  def from_json(cls, raw: dict[str, Any]) -> SarifResult:
    return cls(
      message=SarifMessage.from_json(raw.get("message", {})),
      locations=[
        SarifLocation.from_json(loc)
        for loc in raw.get("locations", [])
      ],
    )


@dataclass(frozen=True)
class SarifRun:
  results: list[SarifResult] = field(default_factory=list)

  @classmethod
  def from_json(cls, raw: dict[str, Any]) -> SarifRun:
    return cls(
      results=[
        SarifResult.from_json(r)
        for r in raw.get("results", [])
      ],
    )


@dataclass(frozen=True)
class SarifLog:
  runs: list[SarifRun] = field(default_factory=list)

  @classmethod
  def from_json(cls, raw: dict[str, Any]) -> SarifLog:
    return cls(
      runs=[
        SarifRun.from_json(r)
        for r in raw.get("runs", [])
      ],
    )


def _discover_queries(query_dir: Path) -> list[Path]:
  """Return all .ql files in *query_dir*, sorted by name."""
  return sorted(query_dir.glob("*.ql"))


def _discover_ql_sources(query_dir: Path) -> list[Path]:
  """Return all .ql and .qll files in *query_dir* recursively."""
  return sorted(
    [*query_dir.rglob("*.ql"), *query_dir.rglob("*.qll")],
  )


def _generate_source_lines(
  source_root: Path,
  query_dir: Path,
) -> Path:
  """Scan source files and generate a .qll with serde line data.

  TODO(github/codeql#20771): the Rust extractor does not expand serde proc-macro
  derives or inspect cfg_attr token-tree content. This function compensates by
  pre-scanning sources and emitting a predicate listing every source line that
  mentions ``serde``. Remove once the extractor supports token-tree extraction.
  """
  out = query_dir / "lib" / "source_lines.qll"
  rows: list[str] = []
  for rs_file in sorted(source_root.rglob("*.rs")):
    rel = str(rs_file.relative_to(source_root))
    try:
      text = rs_file.read_text(encoding="latin-1")
    except OSError:
      continue
    for lineno, line in enumerate(text.splitlines(), 1):
      if "serde" in line:
        rows.append(
          f'  file = "{rel}" and line = {lineno}',
        )

  body = " or\n".join(rows) if rows else "  none()"
  content = (
    f"/** Auto-generated by lint_codeql.py at"
    f" {datetime.datetime.now(datetime.UTC).strftime('%Y-%m-%dT%H:%M:%SZ')}."
    f" Do not edit. */\n"
    "\n"
    "/**\n"
    " * Holds if line `line` in `file` mentions serde.\n"
    " *\n"
    " * File paths are relative to ``pkgs/``.\n"
    " */\n"
    "predicate hasSerdeMention(string file, int line) {\n"
    f"{body}\n"
    "}\n"
  )
  out.write_text(content, encoding="latin-1")
  return out


def _print_sarif_diagnostics(sarif: SarifLog) -> int:
  """Print SARIF results to stderr. Returns the finding count."""
  count = 0
  for run in sarif.runs:
    for r in run.results:
      if not r.locations:
        continue
      phys = r.locations[0].physical_location
      uri = phys.artifact_location.uri
      line = phys.region.start_line
      print(
        f"{uri}:{line}: {r.message.text}", file=sys.stderr,
      )
      count += 1
  return count


def main() -> int:
  try:
    codeql_bin = require_bin("codeql")
  except FileNotFoundError as e:
    print(f"{e}, skipping", file=sys.stderr)
    return RETCODE_SKIP

  repo_root = find_up(
    Path(__file__).resolve().parent,
    is_workspace_root,
    "workspace Cargo.toml",
  )
  query_dir = repo_root / "contrib" / "codeql"
  queries = _discover_queries(query_dir)

  if not queries:
    raise FileNotFoundError("no .ql queries found in contrib/codeql/")

  # Generate source-line data for queries that need raw text.
  generated = _generate_source_lines(
    repo_root / "pkgs",
    query_dir,
  )
  subprocess.run(  # noqa: S603
    [codeql_bin, "query", "format", "-i", "--", str(generated)],
    check=False,
  )

  # Check QL formatting before doing any heavy lifting.
  ql_sources = _discover_ql_sources(query_dir)
  if ql_sources:
    result = subprocess.run(  # noqa: S603
      [
        codeql_bin,
        "query",
        "format",
        "--check-only",
        "--",
        *[str(p) for p in ql_sources],
      ],
      check=False,
    )
    if result.returncode != 0:
      print(
        "error: QL formatting check failed; run "
        "'codeql query format -i' to fix",
        file=sys.stderr,
      )
      return RETCODE_ERR

  # Install CodeQL pack dependencies.
  subprocess.run(  # noqa: S603
    [codeql_bin, "pack", "install", str(query_dir)],
    check=True,
  )

  # Compile queries and treat warnings (e.g. unused imports) as errors.
  result = subprocess.run(  # noqa: S603
    [
      codeql_bin,
      "query",
      "compile",
      "--warnings=error",
      "--",
      *[str(p) for p in queries],
    ],
    check=False,
  )
  if result.returncode != 0:
    print(
      "error: QL compilation failed with warnings",
      file=sys.stderr,
    )
    return 1

  # Create database in a temporary directory.
  with tempfile.TemporaryDirectory() as tmp_dir:
    db_path = Path(tmp_dir) / "db"

    subprocess.run(  # noqa: S603
      [
        codeql_bin,
        "database",
        "create",
        str(db_path),
        "--language=rust",
        f"--source-root={repo_root / 'pkgs'}",
        "--overwrite",
        "-j0",
        "--command=cargo check --features full,_internal",
      ],
      check=True,
    )

    # Run each query and collect diagnostics.
    total_findings = 0
    for query_path in queries:
      sarif_path = Path(tmp_dir) / f"{query_path.stem}.sarif"

      subprocess.run(  # noqa: S603
        [
          codeql_bin,
          "database",
          "analyze",
          str(db_path),
          str(query_path),
          "--format=sarif-latest",
          f"--output={sarif_path}",
        ],
        check=True,
      )

      with sarif_path.open() as f:
        sarif = SarifLog.from_json(json.load(f))
      total_findings += _print_sarif_diagnostics(sarif)

    return RETCODE_ERR if total_findings > 0 else RETCODE_PASS


if __name__ == "__main__":
  try:
    sys.exit(main())
  except Exception as exc:
    print(exc, file=sys.stderr)
    sys.exit(RETCODE_ERR)
