[workspace]
members = [
  "contrib/meta/bazel",
  "pkgs/dev",
  "pkgs/num",
  "pkgs/params",
  "pkgs/p2p_core",
  "pkgs/pkc",
  "pkgs/pow",
  "pkgs/primitives",
  "pkgs/script",
  "pkgs/types",
  "pkgs/types/marker",
]
resolver = "3"

[workspace.dependencies]
ambassador = "0.5.1"
base58ck = { version = "0.5.0", default-features = false }
bitcoin_hashes = { version = "1.2.0", default-features = false }
bitcoin-consensus-encoding = { version = "1.3.0", default-features = false }
bitcoin-internals = { version = "0.7.0", default-features = false }
bitcoin-primitives = { version = "0.103.0", default-features = false }
bitcoin-units = { version = "0.5.0", default-features = false }
delegate = "0.13.5"
divan = "0.1"
hex-conservative = { version = "1.3", default-features = false }
rand_core = { version = "0.10.1", default-features = false }
rstest = "0.25"
serde = { version = "1", default-features = false }
subtle = { version = "2.6.1", default-features = false }
zeroize = { version = "1.9.0", default-features = false }

[workspace.lints.clippy]
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
unwrap_used = "deny"

[workspace.lints.rust]
keyword_idents = { level = "deny", priority = -1 }
missing_debug_implementations = "deny"
non_ascii_idents = "deny"
rust_2021_incompatible_closure_captures = "deny"
rust_2021_incompatible_or_patterns = "deny"
unsafe_code = "deny"
unused_must_use = "deny"

[workspace.package]
authors = ["Kittywhiskers Van Gogh <kittywhiskers@dash.org>"]
edition = "2021"
homepage = "https://dashpay.github.io/base-sdk"
license = "MIT"
repository = "https://github.com/dashpay/base-sdk"
rust-version = "1.85.0"

[profile.release]
lto = true
opt-level = 3
panic = "abort"
strip = true

[profile.dev]
codegen-units = 1
overflow-checks = true
