/**
 * @name Attribute and derivation rules
 * @description Derivation rules: required traits and secret-type restrictions.
 * @kind problem
 * @problem.severity warning
 * @id base-sdk/attrib-rules
 * @tags style
 * @precision high
 */

import lib.fmt
import rust

/** Gets the trait name from an impl block's trait reference. */
string implTraitName(Impl i) {
  result = i.getTrait().(PathTypeRepr).getPath().getSegment().getIdentifier().getText()
}

/** Gets the type name from an impl block's self type. */
string implSelfName(Impl i) {
  result = i.getSelfTy().(PathTypeRepr).getPath().getSegment().getIdentifier().getText()
}

/** Holds if `t` has a derived impl for `traitName`. */
predicate hasDerivedImpl(TypeItem t, string traitName) {
  exists(MacroItems expansion, Impl i |
    expansion = t.getADeriveMacroExpansion() and
    i = expansion.getItem(_) and
    implTraitName(i) = traitName
  )
}

/** Holds if `t` has a manual impl for `traitName`. */
predicate hasManualImpl(TypeItem t, string traitName) {
  exists(Impl i |
    i.getLocation().getFile() = t.getLocation().getFile() and
    implSelfName(i) = t.getName().getText() and
    implTraitName(i) = traitName and
    not exists(MacroItems m | i = m.getItem(_))
  )
}

/** Holds if `t` implements `traitName` via derive or manual impl. */
predicate implementsTrait(TypeItem t, string traitName) {
  hasDerivedImpl(t, traitName) or hasManualImpl(t, traitName)
}

/** Holds if `t` is inside a test module or test file. */
predicate isTestCode(TypeItem t) {
  t.getLocation().getFile().getAbsolutePath().matches("%/tests/%")
  or
  // #[cfg(test)] modules embedded in source files.
  exists(Module m |
    t.getLocation().getFile() = m.getLocation().getFile() and
    t.getLocation().getStartLine() > m.getLocation().getStartLine() and
    t.getLocation().getEndLine() <= m.getLocation().getEndLine() and
    m.getName().getText() = "tests" and
    m.getAnAttr().getMeta().getPath().getSegment().getIdentifier().getText() = "cfg"
  )
}

/** Holds if `t` was generated by a macro expansion. */
predicate isMacroGenerated(TypeItem t) {
  exists(MacroItems m | t = m.getItem(_))
  or
  // Serde's internal generated types (e.g. __FieldVisitor, __Visitor, __Field).
  t.getName().getText().matches("\\_\\_%")
}

/** Holds if `t` is defined inside a function body rather than at module level. */
predicate isLocalType(TypeItem t) {
  exists(Function f |
    f.getLocation().getFile() = t.getLocation().getFile() and
    t.getLocation().getStartLine() > f.getLocation().getStartLine() and
    t.getLocation().getEndLine() <= f.getLocation().getEndLine()
  )
}

/** Holds if `t` is a stateful decoder (wraps external decoder types). */
predicate isDecoder(TypeItem t) { t.getName().getText().matches("%Decoder%") }

/** Holds if `t` holds secret or security-sensitive material. */
predicate isSecretType(TypeItem t) {
  t.getName().getText().regexpMatch(".*(Secret|Private|Seed|Password|Mnemonic|Share).*")
}

/** Holds if `t` is a source type eligible for the "must derive" check. */
predicate isCheckableType(TypeItem t) {
  (t instanceof Struct or t instanceof Enum or t instanceof Union) and
  t.getLocation().getFile().fromSource() and
  not isTestCode(t) and
  not isMacroGenerated(t) and
  not isLocalType(t) and
  not isDecoder(t) and
  not isSecretType(t)
}

/** Holds if `t` is a source type eligible for any check. */
predicate isSourceType(TypeItem t) {
  (t instanceof Struct or t instanceof Enum or t instanceof Union) and
  t.getLocation().getFile().fromSource() and
  not isTestCode(t) and
  not isMacroGenerated(t) and
  not isLocalType(t)
}

/** Gets a required trait name. */
string requiredTrait() { result = ["Clone", "Debug", "PartialEq", "Eq"] }

/** Holds if `name` is a primitive floating-point type. */
predicate isFloatTypeName(string name) { name = ["f32", "f64"] }

/** Gets the type name of a struct field in `s`. */
string structFieldTypeName(Struct s) {
  exists(TypeRepr tr |
    tr = s.getFieldList().(StructFieldList).getAField().getTypeRepr() or
    tr = s.getFieldList().(TupleFieldList).getField(_).getTypeRepr()
  |
    result = tr.(PathTypeRepr).getPath().getSegment().getIdentifier().getText()
  )
}

/** Holds if struct `s` contains a float field, directly or transitively. */
predicate hasFloatField(Struct s) {
  isFloatTypeName(structFieldTypeName(s))
  or
  exists(Struct inner |
    inner.getName().getText() = structFieldTypeName(s) and
    hasFloatField(inner)
  )
}

/**
 * Holds when `trait` should not be required for `t`.
 * Eq is suppressed for structs that transitively contain a float field.
 */
predicate isSuppressed(TypeItem t, string trait) { trait = "Eq" and hasFloatField(t) }

/** Gets a comma-separated list of missing required traits for `t`. */
string missingTraits(TypeItem t) {
  isCheckableType(t) and
  result =
    concat(string trait |
      trait = requiredTrait() and
      not implementsTrait(t, trait) and
      not isSuppressed(t, trait)
    |
      trait, ", " order by trait
    ) and
  result != ""
}

from TypeItem t, string message
where
  (
    isCheckableType(t) and
    exists(string missing |
      missing = missingTraits(t) and
      message = fmt("missing required derivations: {0}", missing)
    )
    or
    isSourceType(t) and
    isSecretType(t) and
    hasDerivedImpl(t, "Debug") and
    message = "secret type must not derive Debug; use a custom impl that redacts content"
  )
select t, message
