#!/usr/bin/env python3
# coding: latin-1

#
# Copyright (c) 2026-present, The Dash Core developers
# SPDX-License-Identifier: MIT
# See the accompanying file LICENSE or https://opensource.org/license/MIT
#

"""Runs CodeQL queries against the workspace."""

from __future__ import annotations

import contextlib
import csv
import datetime
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
  import argparse
  from collections.abc import Iterator

from common import (
  RETCODE_ERR,
  RETCODE_PASS,
  RETCODE_SKIP,
  SOURCE_DIRS,
  declare_verbs,
  require_bin,
  root_dir,
  usable_mem,
  usable_threads,
)

_SOURCE_KEYWORDS = (
  "Serialize", "Deserialize", "Unencodable", "TypeId", "Zeroize", "#[cfg",
)


def _discover_queries(query_dir: Path) -> list[Path]:
  """Return all .ql files in *query_dir*, sorted by name."""
  return sorted(query_dir.glob("*.ql"))


def _discover_ql_sources(query_dir: Path) -> list[Path]:
  """Return all .ql and .qll files in *query_dir* recursively."""
  return sorted(
    [*query_dir.rglob("*.ql"), *query_dir.rglob("*.qll")],
  )


def _generate_source_lines(
  repo_root: Path,
  source_dirs: list[Path],
  query_dir: Path,
) -> Path:
  """Emit a raw source-line predicate for CodeQL queries.

  TODO(github/codeql#20771): the Rust extractor does not expand cfg_attr
  token-tree content. This function compensates by pre-scanning sources and
  emitting lines that match broad keywords.

  Remove once the extractor supports token-tree extraction.
  """
  out = query_dir / "lib" / "source_lines.qll"
  rows: list[str] = []
  for source_dir in source_dirs:
    for rs_file in sorted(source_dir.rglob("*.rs")):
      if "target" in rs_file.parts:
        continue
      rel = str(rs_file.relative_to(repo_root))
      try:
        text = rs_file.read_text(encoding="latin-1")
      except OSError:
        continue
      for lineno, line in enumerate(text.splitlines(), 1):
        if not any(kw in line for kw in _SOURCE_KEYWORDS):
          continue
        escaped = line.strip().replace("\\", "\\\\").replace('"', '\\"')
        rows.append(
          f'  file = "{rel}" and line = {lineno} and content = "{escaped}"',
        )

  body = "\n  or\n".join(rows) if rows else "  none()"
  timestamp = datetime.datetime.now(datetime.UTC).strftime(
    "%Y-%m-%dT%H:%M:%SZ",
  )
  content = (
    f"/** Auto-generated by lint_codeql.py at {timestamp}."
    f" Do not edit. */\n"
    "\n"
    "/**\n"
    " * Holds if `line` in `file` contains look-out keywords.\n"
    " * `content` is the trimmed source text.\n"
    " * File paths are relative to the repository root.\n"
    " */\n"
    "predicate sourceLineContent"
    "(string file, int line, string content) {\n"
    f"{body}\n"
    "}\n"
  )
  out.write_text(content, encoding="latin-1")
  return out


def _print_csv_diagnostics(results_path: Path) -> int:
  """Print CSV results to stderr. Returns the finding count."""
  count = 0
  with results_path.open(newline="") as f:
    for row in csv.reader(f):
      if not row:
        continue
      if len(row) < 6:
        raise ValueError(f"malformed CodeQL CSV row: {row!r}")
      uri = Path(row[4].lstrip("/"))
      line = row[5]
      msg = row[3].replace("\n", " ")
      print(f"{uri}:{line}: {msg}", file=sys.stderr)
      count += 1
  return count


def _locked_pack(pack: str) -> str:
  """Return *pack* pinned to the version the lock file records."""
  lock_file = root_dir() / "maint" / "codeql" / "codeql-pack.lock.yml"
  if not lock_file.is_file():
    raise ValueError(f"missing lock file {lock_file}")
  text = lock_file.read_text(encoding="latin-1")
  match = re.search(
    rf"^\s+{re.escape(pack)}:\s*$\n\s+version:\s*(\S+)\s*$",
    text,
    re.MULTILINE,
  )
  if not match:
    raise ValueError(f"no pinned version for {pack} in {lock_file}")
  return f"{pack}@{match.group(1)}"


def _search_suites(pack: str, names: list[str]) -> list[str]:
  """Return query-suite references under the pinned *pack*."""
  for name in names:
    if not re.fullmatch(r"[A-Za-z0-9._-]+", name):
      raise ValueError(f"invalid --with-suite name: {name!r}")
  return [f"{pack}:codeql-suites/{name}.qls" for name in names]


@contextlib.contextmanager
def _workspace_dirs(
  cache_dir: Path,
  *,
  cache: bool,
) -> Iterator[tuple[Path, Path]]:
  """Yield ``(db_path, results_dir)`` for analysis.

  When *cache* is false a temporary directory is used for both
  the database and the results so no persistent cache is created
  or modified.
  """
  if not cache:
    tmp = Path(tempfile.mkdtemp(prefix="codeql-"))
    try:
      results = tmp / "results"
      results.mkdir()
      yield tmp / "db", results
    finally:
      try:
        shutil.rmtree(tmp)
      except OSError as exc:
        print(
          f"warning: failed to remove {tmp}: {exc}",
          file=sys.stderr,
        )
  else:
    results = cache_dir / "results"
    results.mkdir(parents=True, exist_ok=True)
    yield cache_dir / "db", results


def _parse_args(argv: list[str]) -> argparse.Namespace:
  parser = declare_verbs(
    "Run CodeQL queries against the workspace.",
    {"run": "build a database and evaluate every query"},
  )
  parser.add_argument(
    "-c",
    "--cache",
    action="store_true",
    help="persist the database for faster reruns",
  )
  parser.add_argument(
    "--with-suite",
    action="append",
    default=[],
    dest="suites",
    metavar="NAME",
    help=("run a 'codeql/rust-queries' suite by name (default: none)"),
  )
  return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
  args = _parse_args(argv if argv is not None else sys.argv[1:])

  try:
    codeql_bin = require_bin("codeql")
  except FileNotFoundError as e:
    print(f"{e}, skipping", file=sys.stderr)
    return RETCODE_SKIP

  try:
    require_bin("rustc")
  except FileNotFoundError:
    print(
      "error: rust compiler unavailable, skipping",
      file=sys.stderr,
    )
    return RETCODE_SKIP

  repo_root = root_dir()
  query_dir = repo_root / "maint" / "codeql"
  queries = _discover_queries(query_dir)

  if not queries:
    raise FileNotFoundError("no .ql queries found in maint/codeql/")

  # Generate source-line data for queries that need raw text.
  source_dirs = [repo_root / where for where in SOURCE_DIRS]
  generated = _generate_source_lines(repo_root, source_dirs, query_dir)
  subprocess.run(  # noqa: S603
    [codeql_bin, "query", "format", "-i", str(generated)],
    check=True,
  )

  # Check QL formatting before doing any heavy lifting.
  ql_sources = _discover_ql_sources(query_dir)
  if ql_sources:
    result = subprocess.run(  # noqa: S603
      [
        codeql_bin,
        "query",
        "format",
        "--check-only",
        "--",
        *[str(p) for p in ql_sources],
      ],
      check=False,
    )
    if result.returncode != 0:
      print(
        "error: QL formatting check failed; run "
        "'codeql query format -i' to fix",
        file=sys.stderr,
      )
      return RETCODE_ERR

  try:
    suites = _search_suites(_locked_pack("codeql/rust-queries"), args.suites)
  except ValueError as e:
    print(f"error: {e}", file=sys.stderr)
    return RETCODE_ERR

  # Install CodeQL pack dependencies.
  subprocess.run(  # noqa: S603
    [codeql_bin, "pack", "install", "--no-strict-mode", str(query_dir)],
    check=True,
  )

  cache_dir = query_dir / ".cache"

  with _workspace_dirs(cache_dir, cache=args.cache) as (
    active_db,
    results_dir,
  ):
    db_yml = active_db / "codeql-database.yml"
    if not db_yml.is_file():
      # Remove stale artifacts left behind by a previous failed run.
      if active_db.exists():
        shutil.rmtree(active_db)
      active_db.parent.mkdir(parents=True, exist_ok=True)
      config_file = query_dir / "codeql-config.yml"
      result = subprocess.run(  # noqa: S603
        [
          codeql_bin,
          "database",
          "create",
          str(active_db),
          "--language=rust",
          "--build-mode=none",
          f"--source-root={repo_root}",
          f"--codescanning-config={config_file}",
          f"-j{usable_threads()}",
        ],
        cwd=str(repo_root),
        check=False,
      )
      if result.returncode != RETCODE_PASS or not db_yml.is_file():
        raise RuntimeError(
          f"codeql database create failed (exit {result.returncode}); database"
          f" manifest {db_yml} was not produced",
        )

    # Run each query and collect diagnostics.
    results_path = results_dir / "results.csv"

    subprocess.run(  # noqa: S603
      [
        codeql_bin,
        "database",
        "analyze",
        str(active_db),
        *[str(q) for q in queries],
        *suites,
        "--format=csv",
        f"--output={results_path}",
        f"--threads={usable_threads()}",
        f"--ram={usable_mem()}",
      ],
      check=True,
    )

    total_findings = _print_csv_diagnostics(results_path)

  return RETCODE_ERR if total_findings > 0 else RETCODE_PASS


if __name__ == "__main__":
  try:
    sys.exit(main())
  except Exception as exc:  # noqa: BLE001
    print(exc, file=sys.stderr)
    sys.exit(RETCODE_ERR)
