// @ts-check

const sharedRules = {
  "arrow-body-style": ["error", "as-needed"],
  curly: "error",
  "default-case-last": "error",
  "default-case": "error",
  "dot-notation": "error",
  eqeqeq: ["error", "always"],
  "func-style": ["error", "declaration", { allowArrowFunctions: true }],
  "no-async-promise-executor": "error",
  "no-caller": "error",
  "no-duplicate-case": "error",
  "no-eval": "error",
  "no-extend-native": "error",
  "no-fallthrough": "error",
  "no-implicit-coercion": "error",
  "no-implied-eval": "error",
  "no-iterator": "error",
  "no-new-func": "error",
  "no-param-reassign": "error",
  "no-promise-executor-return": "error",
  "no-proto": "error",
  "no-redeclare": "error",
  "no-return-await": "error",
  "no-self-compare": "error",
  "no-shadow": "error",
  "no-throw-literal": "error",
  "no-undef": "error",
  "no-unmodified-loop-condition": "error",
  "no-unreachable-loop": "error",
  "no-unreachable": "error",
  "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
  "no-use-before-define": ["error", { functions: false }],
  "no-var": "error",
  "object-shorthand": ["error", "always"],
  "prefer-arrow-callback": "error",
  "prefer-const": "error",
  "prefer-object-spread": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "prefer-template": "error",
  quotes: ["error", "double", { avoidEscape: true }],
  "require-await": "error",
  semi: ["error", "always"],
};

export default [
  {
    ignores: ["docs/**", "contrib/samples/**", "**/pkg/**"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        console: "readonly",
        module: "readonly",
        process: "readonly",
        require: "readonly",
        setTimeout: "readonly",
      },
    },
    rules: sharedRules,
  },
  {
    files: ["docs/**/*.js", "contrib/samples/**/*.js"],
    ignores: ["**/pkg/**"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        console: "readonly",
        document: "readonly",
        navigator: "readonly",
        performance: "readonly",
        self: "readonly",
        TextDecoder: "readonly",
        TextEncoder: "readonly",
        Uint8Array: "readonly",
        URL: "readonly",
        Worker: "readonly",
        clearTimeout: "readonly",
        setTimeout: "readonly",
      },
    },
    rules: sharedRules,
  },
];
