/**
 * Copyright (c) 2026-present, The Dash Core developers
 * SPDX-License-Identifier: MIT
 * See the accompanying file LICENSE or https://opensource.org/license/MIT
 *
 * @description Common predicates for filtering types by context.
 */

import lib.files
import lib.traits
import rust

/** Holds if `t` is defined inside a function body rather than at module level. */
predicate isLocalType(TypeItem t) {
  exists(Function f |
    fileOf(f) = fileOf(t) and
    startLine(t) > startLine(f) and
    endLine(t) <= endLine(f)
  )
}

/** Holds if `t` was generated by a macro expansion. */
predicate isMacroGenerated(TypeItem t) {
  exists(MacroItems m | t = m.getItem(_))
  or
  // Serde's internal generated types (e.g. __FieldVisitor, __Visitor, __Field).
  t.getName().getText().matches("\\_\\_%")
}

/** Holds if `t` is inside a test module or test file. */
predicate isTestCode(TypeItem t) {
  fileOf(t).getAbsolutePath().matches("%/tests/%")
  or
  // #[cfg(test)] modules embedded in source files.
  exists(Module m |
    fileOf(t) = fileOf(m) and
    startLine(t) > startLine(m) and
    endLine(t) <= endLine(m) and
    m.getName().getText() = "tests" and
    m.getAnAttr().getMeta().getPath().getSegment().getIdentifier().getText() = "cfg"
  )
}

/** Holds if `t` carries `#[derive(Unencodable)]` or `#[derive(dash_types::Unencodable)]`. */
predicate isNotEncodable(TypeItem t) {
  exists(Attr a |
    a = t.getAnAttr() and
    a.getMeta().getPath().getSegment().getIdentifier().getText() = "derive" and
    a.getMeta().getTokenTree().toAbbreviatedString().regexpMatch(".*\\bUnencodable\\b.*")
  )
}

/** Holds if `t` holds secret or security-sensitive material. */
predicate isSecretType(TypeItem t) {
  t.getName().getText().regexpMatch(".*(Secret|Private|Seed|Password|Mnemonic|Share).*") and
  // Exclude types whose name contains "Shared" (e.g. SharedState),
  // which match the Share substring but are not secret holders.
  not t.getName().getText().regexpMatch(".*Shared.*")
}

/** Holds if `t` is a source type eligible for any check. */
predicate isSourceType(TypeItem t) {
  (t instanceof Struct or t instanceof Enum or t instanceof Union) and
  fileOf(t).fromSource() and
  not isTestCode(t) and
  not isMacroGenerated(t) and
  not isLocalType(t)
}

/** Holds if `t` is an iterator type (name ends with Iterator or Iter). */
predicate isIteratorType(TypeItem t) {
  t.getName().getText().matches("%Iterator") or
  t.getName().getText().matches("%Iter")
}

/** Holds if `t` is an error type (name ends with Error, Invalid, TooLong, or TooShort). */
predicate isErrorType(TypeItem t) {
  t.getName().getText().matches("%Error") or
  t.getName().getText().matches("%Invalid") or
  t.getName().getText().matches("%TooLong") or
  t.getName().getText().matches("%TooShort")
}

/** Holds if `t` is a dispatch/message type (name ends with Message). */
predicate isDispatchType(TypeItem t) { t.getName().getText().matches("%Message") }

/** Holds if `t` is an opaque single-field wrapper in the pkc crate. */
predicate isOpaqueType(TypeItem t) {
  t instanceof Struct and
  exists(string path |
    path = fileOf(t).getAbsolutePath() and
    path.matches("%/pkgs/pkc/%")
  ) and
  isSingleTupleField(t)
}

/** Holds if struct `t` has exactly one unnamed (tuple) field. */
predicate isSingleTupleField(TypeItem t) {
  exists(Struct s |
    s = t and
    count(s.getFieldList().(TupleFieldList).getField(_)) = 1
  )
}

/** Holds if `t` has a lifetime parameter in its generic params. */
predicate hasLifetime(TypeItem t) {
  exists(t.getGenericParamList().getAGenericParam().(LifetimeParam))
}

/** Gets the crate directory prefix for a source type. */
string cratePrefix(TypeItem t) {
  exists(string path |
    path = fileOf(t).getAbsolutePath() and
    result = path.regexpCapture("(.*/pkgs/[^/]+/).*", 1)
  )
}

/** Holds if struct `s` contains a float field, directly or transitively. */
predicate hasFloatField(TypeItem t) {
  typeFieldName(t) = ["f32", "f64"]
  or
  exists(TypeItem inner |
    inner.getName().getText() = typeFieldName(t) and
    cratePrefix(inner) = cratePrefix(t) and
    hasFloatField(inner)
  )
}

/** Gets the type name of a field in struct `s`. */
string structFieldTypeName(Struct s) {
  exists(TypeRepr tr |
    tr = s.getFieldList().(StructFieldList).getAField().getTypeRepr() or
    tr = s.getFieldList().(TupleFieldList).getField(_).getTypeRepr()
  |
    result = tr.(PathTypeRepr).getPath().getSegment().getIdentifier().getText()
  )
}

/** Gets the type name of a field in enum variant of `e`. */
string enumFieldTypeName(Enum e) {
  exists(Variant v, TypeRepr tr |
    v = e.getVariantList().getAVariant() and
    (
      tr = v.getFieldList().(StructFieldList).getAField().getTypeRepr() or
      tr = v.getFieldList().(TupleFieldList).getField(_).getTypeRepr()
    )
  |
    result = tr.(PathTypeRepr).getPath().getSegment().getIdentifier().getText()
  )
}

/** Gets the type name of a field in type item `t` (struct or enum). */
string typeFieldName(TypeItem t) {
  result = structFieldTypeName(t)
  or
  result = enumFieldTypeName(t)
}
