/**
 * Copyright (c) 2026-present, The Dash Core developers
 * SPDX-License-Identifier: MIT
 * See the accompanying file LICENSE or https://opensource.org/license/MIT
 *
 * Common predicates for filtering types by context.
 */

import lib.traits
import rust

/** Holds if `t` is inside a test module or test file. */
predicate isTestCode(TypeItem t) {
  t.getLocation().getFile().getAbsolutePath().matches("%/tests/%")
  or
  // #[cfg(test)] modules embedded in source files.
  exists(Module m |
    t.getLocation().getFile() = m.getLocation().getFile() and
    t.getLocation().getStartLine() > m.getLocation().getStartLine() and
    t.getLocation().getEndLine() <= m.getLocation().getEndLine() and
    m.getName().getText() = "tests" and
    m.getAnAttr().getMeta().getPath().getSegment().getIdentifier().getText() = "cfg"
  )
}

/** Holds if `t` was generated by a macro expansion. */
predicate isMacroGenerated(TypeItem t) {
  exists(MacroItems m | t = m.getItem(_))
  or
  // Serde's internal generated types (e.g. __FieldVisitor, __Visitor, __Field).
  t.getName().getText().matches("\\_\\_%")
}

/** Holds if `t` is defined inside a function body rather than at module level. */
predicate isLocalType(TypeItem t) {
  exists(Function f |
    f.getLocation().getFile() = t.getLocation().getFile() and
    t.getLocation().getStartLine() > f.getLocation().getStartLine() and
    t.getLocation().getEndLine() <= f.getLocation().getEndLine()
  )
}

/** Gets the type name of a struct field in `s`. */
string structFieldTypeName(Struct s) {
  exists(TypeRepr tr |
    tr = s.getFieldList().(StructFieldList).getAField().getTypeRepr() or
    tr = s.getFieldList().(TupleFieldList).getField(_).getTypeRepr()
  |
    result = tr.(PathTypeRepr).getPath().getSegment().getIdentifier().getText()
  )
}

/**
 * Holds if `t` is a newtype wrapper with manual PartialEq (opaque FFI
 * wrapper whose inner type may not implement serde).
 */
predicate isOpaqueWrapper(TypeItem t) {
  t instanceof Struct and
  exists(t.(Struct).getFieldList().(TupleFieldList).getField(0)) and
  not exists(t.(Struct).getFieldList().(TupleFieldList).getField(1)) and
  not hasDerivedImpl(t, "PartialEq") and
  hasManualImpl(t, "PartialEq")
}

/** Holds if struct `s` contains a float field, directly or transitively. */
predicate hasFloatField(Struct s) {
  structFieldTypeName(s) = ["f32", "f64"]
  or
  exists(Struct inner |
    inner.getName().getText() = structFieldTypeName(s) and
    hasFloatField(inner)
  )
}
