//
// Copyright (c) 2026-present, The Dash Core developers
// SPDX-License-Identifier: MIT
// See the accompanying file LICENSE or https://opensource.org/license/MIT
//

// End-to-end smoke test of the dash_pkc C++ wrapper: sign/verify on
// both schemes, cross-scheme reserialization, aggregation, the
// Dash Core threshold flow, BLS-IES, and a legacy KAT generated by
// dashbls (corpus/bls_chia_legacy_threshold.json).

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include <dash_pkc/dash_pkc.hpp>

namespace {

int g_failures = 0;

#define CHECK(cond)                                                          \
    do {                                                                     \
        if (!(cond)) {                                                       \
            std::fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); \
            ++g_failures;                                                    \
        }                                                                    \
    } while (0)

std::vector<uint8_t> FromHex(const std::string& hex)
{
    std::vector<uint8_t> out(hex.size() / 2);
    for (size_t i = 0; i < out.size(); ++i) {
        out[i] = static_cast<uint8_t>(std::stoul(hex.substr(2 * i, 2), nullptr, 16));
    }
    return out;
}

std::vector<uint8_t> Seq(size_t n, uint8_t start)
{
    std::vector<uint8_t> out(n);
    for (size_t i = 0; i < n; ++i) {
        out[i] = static_cast<uint8_t>(start + i);
    }
    return out;
}

void TestSignVerifyBothSchemes()
{
    const auto seed = Seq(32, 1);
    auto sk = dash_pkc::PrivateKey::KeyGen(seed);
    CHECK(sk.has_value());

    const auto hash = Seq(32, 0x40);
    for (const bool legacy : {false, true}) {
        auto pk = sk->GetG1Element(legacy);
        CHECK(pk.has_value());
        auto sig = sk->Sign(hash, legacy);
        CHECK(sig.has_value());

        const dash_pkc::CoreMPL scheme(legacy);
        CHECK(scheme.Verify(*pk, hash, *sig));

        // Wrong message and wrong scheme must both fail.
        CHECK(!scheme.Verify(*pk, Seq(32, 0x41), *sig));
        CHECK(!dash_pkc::CoreMPL(!legacy).Verify(*pk, hash, *sig));
    }

    // Legacy signing is hash-only, as in dashbls.
    auto bad = sk->Sign(Seq(31, 0), true);
    CHECK(!bad.has_value() && bad.error() == dash_pkc::Error::InvalidMessageLength);
    // Basic signing accepts arbitrary lengths.
    CHECK(sk->Sign(Seq(31, 0), false).has_value());
}

void TestSerializationRoundTrips()
{
    auto sk = dash_pkc::PrivateKey::KeyGen(Seq(32, 7));
    CHECK(sk.has_value());

    // Secret key round-trip.
    const auto sk_bytes = sk->SerializeToArray();
    auto sk2 = dash_pkc::PrivateKey::FromBytes(sk_bytes);
    CHECK(sk2.has_value() && *sk2 == *sk);
    // modOrder is tolerated (ignored) for dashbls call compatibility.
    CHECK(dash_pkc::PrivateKey::FromBytes(sk_bytes, /*modOrder=*/true).has_value());

    // Null (default-constructed) objects: zero serialization, null
    // equality, failing operations.
    dash_pkc::PrivateKey null_sk;
    dash_pkc::G1Element null_pk;
    CHECK(null_sk.IsNull() && null_pk.IsNull());
    CHECK(null_pk == dash_pkc::G1Element{});
    CHECK(null_pk != *sk->GetG1Element(false));
    const auto null_ser = null_pk.SerializeToArray(false);
    CHECK(std::all_of(null_ser.begin(), null_ser.end(), [](uint8_t c) { return c == 0; }));
    CHECK(!null_sk.Sign(sk_bytes, false).has_value());
    CHECK(!dash_pkc::DHKeyExchange(null_sk, null_pk).has_value());

    // The same group element serializes differently per scheme but
    // parses back equal: the fork-transition reserialization path.
    auto pk = sk->GetG1Element(true);
    CHECK(pk.has_value());
    const auto legacy_bytes = pk->SerializeToArray(true);
    const auto basic_bytes = pk->SerializeToArray(false);
    CHECK(std::memcmp(legacy_bytes.data(), basic_bytes.data(), legacy_bytes.size()) != 0);

    auto from_legacy = dash_pkc::G1Element::FromBytes(legacy_bytes, true);
    auto from_basic = dash_pkc::G1Element::FromBytes(basic_bytes, false);
    CHECK(from_legacy.has_value() && from_basic.has_value());
    CHECK(*from_legacy == *from_basic);
    CHECK(*from_legacy == *pk);

    // Parsing bytes under the wrong scheme must not round-trip
    // silently: either reject or produce a different element.
    auto cross = dash_pkc::G1Element::FromBytes(basic_bytes, true);
    CHECK(!cross.has_value() || *cross != *pk);

    // Signature round-trip on both schemes.
    auto sig = sk->Sign(Seq(32, 9), true);
    CHECK(sig.has_value());
    auto sig_rt = dash_pkc::G2Element::FromBytes(sig->SerializeToArray(true), true);
    CHECK(sig_rt.has_value() && *sig_rt == *sig);
    auto sig_rt_basic = dash_pkc::G2Element::FromBytes(sig->SerializeToArray(false), false);
    CHECK(sig_rt_basic.has_value() && *sig_rt_basic == *sig);

    // Zero / garbage inputs are rejected.
    const std::vector<uint8_t> zeros48(48, 0);
    CHECK(!dash_pkc::G1Element::FromBytes(zeros48, false).has_value());
    CHECK(!dash_pkc::G1Element::FromBytes(zeros48, true).has_value());
    const std::vector<uint8_t> zeros32(32, 0);
    CHECK(!dash_pkc::PrivateKey::FromBytes(zeros32).has_value());
}

void TestAggregation()
{
    for (const bool legacy : {false, true}) {
        const dash_pkc::CoreMPL scheme(legacy);
        const auto hash = Seq(32, 0x11);

        std::vector<dash_pkc::PrivateKey> sks;
        std::vector<dash_pkc::G1Element> pks;
        std::vector<dash_pkc::G2Element> sigs;
        for (uint8_t i = 1; i <= 3; ++i) {
            auto sk = dash_pkc::PrivateKey::KeyGen(std::vector<uint8_t>(32, i));
            CHECK(sk.has_value());
            pks.push_back(*sk->GetG1Element(legacy));
            sigs.push_back(*sk->Sign(hash, legacy));
            sks.push_back(std::move(*sk));
        }

        // Insecure aggregation: sig over the same message verifies
        // against the aggregated key.
        auto agg_pk = scheme.Aggregate(pks);
        auto agg_sig = scheme.Aggregate(sigs);
        CHECK(agg_pk.has_value() && agg_sig.has_value());
        CHECK(scheme.Verify(*agg_pk, hash, *agg_sig));

        // Secure (delinearized) aggregation round-trip.
        auto sec_sig = scheme.AggregateSecure(pks, sigs, hash);
        CHECK(sec_sig.has_value());
        CHECK(scheme.VerifySecure(pks, *sec_sig, hash));
        CHECK(!scheme.VerifySecure(pks, *agg_sig, hash));

        // Aggregate secret keys: sig by the sum key equals the
        // aggregate signature.
        auto agg_sk = dash_pkc::PrivateKey::Aggregate(sks);
        CHECK(agg_sk.has_value());
        CHECK(*agg_sk->Sign(hash, legacy) == *agg_sig);

        // SubInsecure removes one signer.
        auto sub = agg_sig->SubInsecure(sigs[2]);
        CHECK(sub.has_value());
        auto pk01 = scheme.Aggregate({pks[0], pks[1]});
        CHECK(pk01.has_value() && scheme.Verify(*pk01, hash, *sub));

        // AggregateVerify over per-signer messages.
        std::vector<std::vector<uint8_t>> msgs;
        std::vector<dash_pkc::G2Element> msg_sigs;
        for (uint8_t i = 0; i < 3; ++i) {
            msgs.push_back(Seq(32, static_cast<uint8_t>(0x20 + i)));
            msg_sigs.push_back(*sks[i].Sign(msgs.back(), legacy));
        }
        auto agg2 = scheme.Aggregate(msg_sigs);
        CHECK(agg2.has_value());
        CHECK(scheme.AggregateVerify(pks, msgs, *agg2));
        msgs[0][0] ^= 1;
        CHECK(!scheme.AggregateVerify(pks, msgs, *agg2));
    }
}

// The Dash Core DKG shape: masters are polynomial coefficients,
// shares are evaluations at member ids, threshold-many share
// signatures recover the master signature.
void TestThreshold()
{
    for (const bool legacy : {false, true}) {
        const dash_pkc::CoreMPL scheme(legacy);
        const auto hash = Seq(32, 0x77);

        std::vector<dash_pkc::PrivateKey> master_sks;
        std::vector<dash_pkc::G1Element> master_pks;
        for (uint8_t i = 1; i <= 2; ++i) {
            auto sk = dash_pkc::PrivateKey::KeyGen(std::vector<uint8_t>(32, static_cast<uint8_t>(0x30 + i)));
            CHECK(sk.has_value());
            master_pks.push_back(*sk->GetG1Element(legacy));
            master_sks.push_back(std::move(*sk));
        }

        std::vector<std::vector<uint8_t>> ids;
        std::vector<dash_pkc::G2Element> share_sigs;
        for (uint8_t i = 1; i <= 3; ++i) {
            std::vector<uint8_t> id(32, 0);
            id[0] = i;
            auto sk_share = dash_pkc::Threshold::PrivateKeyShare(master_sks, id);
            auto pk_share = dash_pkc::Threshold::PublicKeyShare(master_pks, id);
            CHECK(sk_share.has_value() && pk_share.has_value());

            // Secret and public share derivations commute.
            CHECK(*sk_share->GetG1Element(legacy) == *pk_share);

            auto sig_share = sk_share->Sign(hash, legacy);
            CHECK(sig_share.has_value());
            CHECK(scheme.Verify(*pk_share, hash, *sig_share));
            if (i <= 2) {
                ids.push_back(id);
                share_sigs.push_back(std::move(*sig_share));
            }
        }

        // threshold = 2: two share signatures recover the master
        // signature, which verifies under the master public key.
        auto recovered = dash_pkc::Threshold::SignatureRecover(share_sigs, ids);
        CHECK(recovered.has_value());
        CHECK(scheme.Verify(master_pks[0], hash, *recovered));
        CHECK(*recovered == *master_sks[0].Sign(hash, legacy));

        // One share is not enough.
        auto insufficient = dash_pkc::Threshold::SignatureRecover({share_sigs[0]}, {ids[0]});
        CHECK(!insufficient.has_value());
    }
}

// KAT from corpus/bls_chia_legacy_threshold.json, generated against
// dashbls / Dash Core: a legacy threshold signature must verify
// under the legacy scheme.
void TestLegacyKat()
{
    // dashbls byte-reverses the sign hash (uint256 display order)
    // before signing; do the same here.
    auto hash = FromHex("b6d8ee31bbd375dfd55d5fb4b02cfccc68709e64f4c5ffcd3895ceb46540311d");
    std::reverse(hash.begin(), hash.end());
    const auto pk_bytes =
        FromHex("97a12b918eac73718d55b7fca60435ec0b442d7e24b45cbd80f5cf2ea2e14c4164333fffdb00d27e309abbafacaa9c34");
    const auto sig_bytes = FromHex(
        "031c536960c9c44efefa4a3334d2d1b808f46abe121cd14a1d0b6ee6b6dca85fd3087d86fe5b1327e6792be53f4ed4df"
        "19c3af3aac79c0bb9dc36fc2a30ba566de6a82cd3e4af2d6654cbe02bb52769a06c1644a4c63b3c3a6fd16e5e68e5c0b");

    auto pk = dash_pkc::G1Element::FromBytes(pk_bytes, true);
    auto sig = dash_pkc::G2Element::FromBytes(sig_bytes, true);
    CHECK(pk.has_value() && sig.has_value());
    CHECK(dash_pkc::LegacySchemeMPL().Verify(*pk, hash, *sig));
    CHECK(!dash_pkc::BasicSchemeMPL().Verify(*pk, hash, *sig));
}

void TestIes()
{
    auto sk = dash_pkc::PrivateKey::KeyGen(Seq(32, 0x51));
    CHECK(sk.has_value());
    const auto entropy = Seq(dash_pkc::IES_ENTROPY_SIZE, 0xA0);
    const auto plaintext = Seq(32, 0x61);

    for (const bool legacy : {false, true}) {
        auto pk = sk->GetG1Element(legacy);
        CHECK(pk.has_value());

        auto blob = dash_pkc::IESBlob::Encrypt(*pk, plaintext, entropy);
        CHECK(blob.has_value());
        auto plain = blob->Decrypt(*sk, 0, legacy);
        CHECK(plain.has_value() && *plain == plaintext);

        // Wire round-trip.
        auto reparsed = dash_pkc::IESBlob::FromBytes(blob->Serialize());
        CHECK(reparsed.has_value());
        auto plain2 = reparsed->Decrypt(*sk, 0, legacy);
        CHECK(plain2.has_value() && *plain2 == plaintext);

        // Wrong key fails to produce the plaintext.
        auto other = dash_pkc::PrivateKey::KeyGen(Seq(32, 0x52));
        auto wrong = other.has_value() ? blob->Decrypt(*other, 0, legacy) : tl::expected<std::vector<uint8_t>, dash_pkc::Error>(tl::unexpected(dash_pkc::Error::InternalError));
        CHECK(!wrong.has_value() || *wrong != plaintext);

        // Unaligned plaintext and short entropy are rejected.
        CHECK(!dash_pkc::IESBlob::Encrypt(*pk, Seq(15, 0), entropy).has_value());
        CHECK(!dash_pkc::IESBlob::Encrypt(*pk, plaintext, Seq(32, 0)).has_value());
    }

    // Multi-recipient: per-recipient plaintexts, per-index IVs.
    auto sk2 = dash_pkc::PrivateKey::KeyGen(Seq(32, 0x53));
    CHECK(sk2.has_value());
    const std::vector<dash_pkc::G1Element> recipients{*sk->GetG1Element(false), *sk2->GetG1Element(false)};
    const std::vector<std::vector<uint8_t>> plaintexts{Seq(16, 0x71), Seq(48, 0x72)};

    auto multi = dash_pkc::IESMultiBlob::Encrypt(recipients, plaintexts, entropy);
    CHECK(multi.has_value());
    CHECK(multi->BlobCount() == 2);
    auto p0 = multi->Decrypt(0, *sk);
    auto p1 = multi->Decrypt(1, *sk2);
    CHECK(p0.has_value() && *p0 == plaintexts[0]);
    CHECK(p1.has_value() && *p1 == plaintexts[1]);
    CHECK(!multi->Decrypt(2, *sk).has_value());

    auto multi_rt = dash_pkc::IESMultiBlob::FromBytes(multi->Serialize());
    CHECK(multi_rt.has_value());
    auto p0_rt = multi_rt->Decrypt(0, *sk);
    CHECK(p0_rt.has_value() && *p0_rt == plaintexts[0]);
}

void TestDhExchange()
{
    auto a = dash_pkc::PrivateKey::KeyGen(Seq(32, 0x81));
    auto b = dash_pkc::PrivateKey::KeyGen(Seq(32, 0x82));
    CHECK(a.has_value() && b.has_value());

    for (const bool legacy : {false, true}) {
        auto shared_ab = dash_pkc::DHKeyExchange(*a, *b->GetG1Element(legacy));
        auto shared_ba = dash_pkc::DHKeyExchange(*b, *a->GetG1Element(legacy));
        CHECK(shared_ab.has_value() && shared_ba.has_value());
        CHECK(*shared_ab == *shared_ba);
    }
}

} // namespace

void TestSession()
{
    const auto entropy = Seq(32, 0xE0);
    auto session = dash_pkc::Session::Create(entropy);
    CHECK(session.has_value());
    CHECK(!dash_pkc::Session::Create(Seq(16, 0)).has_value());

    auto sk = dash_pkc::PrivateKey::KeyGen(Seq(32, 0x91));
    CHECK(sk.has_value());
    const auto hash = Seq(32, 0x92);

    for (const bool legacy : {false, true}) {
        auto pk = sk->GetG1Element(legacy);
        auto sig = sk->Sign(hash, legacy);
        CHECK(pk.has_value() && sig.has_value());

        // Repeated session verifies hit the hash-to-G2 cache and
        // must agree with the uncached path.
        for (int rep = 0; rep < 3; ++rep) {
            CHECK(session->Verify(*pk, hash, *sig, legacy));
        }
        CHECK(!session->Verify(*pk, Seq(32, 0x93), *sig, legacy));
        CHECK(session->Verify(*pk, hash, *sig, legacy) ==
              dash_pkc::CoreMPL(legacy).Verify(*pk, hash, *sig));

        // Aggregated verification through the session.
        auto sk2 = dash_pkc::PrivateKey::KeyGen(Seq(32, 0x94));
        const auto hash2 = Seq(32, 0x95);
        auto sig2 = sk2->Sign(hash2, legacy);
        auto agg = dash_pkc::CoreMPL(legacy).Aggregate({*sig, *sig2});
        CHECK(agg.has_value());
        const std::vector<dash_pkc::G1Element> pks{*pk, *sk2->GetG1Element(legacy)};
        const std::vector<std::vector<uint8_t>> msgs{hash, hash2};
        for (int rep = 0; rep < 2; ++rep) {
            CHECK(session->VerifyAggregated(pks, msgs, *agg, legacy));
        }
        CHECK(!session->VerifyAggregated(pks, {hash2, hash}, *agg, legacy));

        // Pass-through paths agree with their plain equivalents.
        CHECK(session->ParsePublicKey(pk->SerializeToArray(legacy), legacy).has_value());
        CHECK(session->ParseSignature(sig->SerializeToArray(legacy), legacy).has_value());
    }
}

int main()
{
    TestSignVerifyBothSchemes();
    TestSerializationRoundTrips();
    TestAggregation();
    TestThreshold();
    TestLegacyKat();
    TestIes();
    TestDhExchange();
    TestSession();

    if (g_failures != 0) {
        std::fprintf(stderr, "%d check(s) failed\n", g_failures);
        return EXIT_FAILURE;
    }
    std::printf("all checks passed\n");
    return EXIT_SUCCESS;
}
