always-allow-substitutes = true
bash-prompt-prefix = (nix:$name)\040
build-users-group = nixbld
experimental-features = nix-command flakes
sandbox = false

substituters = https://cache.nixos.org/ https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
