name: Deploy docs

on:
  push:
    branches: [develop]
  pull_request:
    paths:
      - pkgs/**
      - docs/**
      - .github/workflows/pages.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build site

    defaults:
      run:
        shell: nix develop ./contrib/nix#ci --command bash -eo pipefail {0}
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Test documentation tooling
        run: pytest

      - name: Manage cargo registry
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-deps-${{ hashFiles('Cargo.lock', 'docs/samples/Cargo.lock') }}
          restore-keys: cargo-deps-

      - name: Build documentation
        run: python3 docs/build_docs.py build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/.site

  deploy:
    name: Deploy to GitHub Pages
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    needs: build
    runs-on: ubuntu-24.04-arm

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
