name: "dash-num"

on:
  workflow_dispatch:
  push:
    paths: &paths
      - pkgs/num/**
      - Cargo.lock
      - Cargo.toml
      - .github/workflows/pkg_num.yml
      - .github/workflows/build_stable.yml
      - .github/workflows/build_nightly.yml
      - contrib/nix/**
      - pyproject.toml
      - rust-toolchain.toml
      - uv.lock
  pull_request:
    paths: *paths

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  stable:
    uses: ./.github/workflows/build_stable.yml
    with:
      package: dash-num
      package_dir: num

  nightly:
    uses: ./.github/workflows/build_nightly.yml
    with:
      package: dash-num
      package_dir: num
    secrets: inherit
