name: "dash-params"

on:
  workflow_dispatch:
  push:
    paths:
      - pkgs/params/**
      - pkgs/num/**
      - pkgs/primitives/**
      - pkgs/script/**
      - Cargo.lock
      - Cargo.toml
      - .github/workflows/pkg_params.yml
      - .github/workflows/build_stable.yml
      - .github/workflows/build_nightly.yml
      - contrib/nix/**
      - rust-toolchain.toml
      - uv.lock
  pull_request:
    paths:
      - pkgs/params/**
      - pkgs/num/**
      - pkgs/primitives/**
      - pkgs/script/**
      - Cargo.lock
      - Cargo.toml
      - .github/workflows/pkg_params.yml
      - .github/workflows/build_stable.yml
      - .github/workflows/build_nightly.yml
      - contrib/nix/**
      - rust-toolchain.toml
      - uv.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  stable:
    uses: ./.github/workflows/build_stable.yml
    with:
      package: dash-params
      package_dir: params

  nightly:
    uses: ./.github/workflows/build_nightly.yml
    with:
      package: dash-params
      package_dir: params
    secrets: inherit
